# Generated by Django 4.2.7 on 2025-11-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
