# Generated by Django 6.0 on 2025-12-31 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_dashboard", "0004_add_waste_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Panchayath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Panchayaths",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="ward",
            options={"ordering": ["panchayath", "ward_number"]},
        ),
        migrations.AddField(
            model_name="ward",
            name="panchayath",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wards",
                to="user_dashboard.panchayath",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ward",
            unique_together={("panchayath", "ward_number")},
        ),
        migrations.RemoveField(
            model_name="ward",
            name="panchayat_municipality",
        ),
    ]
